config/routes.rb
Rails.application.routes.draw do
  Rails.application.routes.default_url_options[:host] = "localhost:3000"
  get 'general_shopping_list/index'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  get 'public_recipes', to: 'recipes#public', as: 'public'
  root "recipes#public"
  resources :foods
  resources :recipes do
    resources :recipe_foods
    end
  resources :public_recipes
  resources :general_shopping_list

end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy
  has_many :foods, through: :recipe_foods, dependent: :destroy

  validates :name, presence: true
  validates :preparation_time, presence: true

  validates :cooking_time, presence: true

  validates :description, presence: true
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!, except: [:public]

  def public
    @recipes = Recipe.where(public: true)
  end

  def index
    @recipes = Recipe.where(user_id: current_user.id)
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)

    if @recipe.save
      flash[:success] = 'Recipe added successfully'
      redirect_to recipes_path
    else
      flash.now[:error] = 'Error: Recipe could not be added'
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @recipe = Recipe.includes(:foods).find(params[:id])
    @foods = @recipe.foods
    @recipe_foods = @recipe.recipe_foods
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    if @recipe.destroy
      flash[:success] = 'Recipe was successfully deleted.'
      redirect_to recipes_path
    else
      flash[:error] = 'Something went wrong'
      render :show
    end
  end

  def recipe_params
    my_recipe = params.require(:recipe).permit(:name, :description, :cooking_time, :preparation_time, :public)
    my_recipe[:user] = current_user
    my_recipe
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.erb
<%= form_with model: recipe, url: recipes_path  do |form| %>
    <h2> <%= recipe.id %> </h2>
    <div class="d-flex flex-column justify-content-center align-items-center">
        <div>
         <%= form.label :name %><br />
          <%= form.text_field :name, autofocus: true, autocomplete: "text" %>
          <% recipe.errors.full_messages_for(:name).each do |message| %>
            <div><%= message %></div>
          <% end %>
        </div>
   
        <div>
         <%= form.label :preparation_time %><br />
          <%= form.number_field :preparation_time, autofocus: true %>
          <% recipe.errors.full_messages_for(:preparation_time).each do |message| %>
            <div><%= message %></div>
          <% end %>
        </div>
  
        <div>
         <%= form.label :cooking_time %><br />
          <%= form.number_field :cooking_time, autofocus: true %>
          <% recipe.errors.full_messages_for(:cooking_time).each do |message| %>
            <div><%= message %></div>
          <% end %>
        </div>
  
        <div>
         <%= form.label :description %><br />
          <%= form.text_field :description, autofocus: true %>
          <% recipe.errors.full_messages_for(:description).each do |message| %>
            <div><%= message %></div>
          <% end %>
        </div>
        <div class="form-check form-switch">
          <%= form.check_box :public, class:"form-check-input", id:"flexSwitchCheckDefault" %>
          <label class="form-check-label" for="flexSwitchCheckDefault">Public</label>
        </div>
        <button type="submit" class="btn btn-primary">Create Recipe</button>
    </div>

<% end %>

app/views/recipes/_recipe.html.erb
<%
=begin%>
 <h1> Name: <%= recipe.name %></h1>
<div id="<%= dom_id recipe %>">
     <p>Preparation time: <%= recipe.preperation_time %></p>
     <p>Cooking time: <%= recipe.cooking_time %></p>
</div> 
<%
=end%>

<div>
    <h1 class="text-center" > <%= recipe.name %></h1>
    <div class="d-flex justify-content-between mx-5" id="<%= dom_id recipe %>">
     <div>
        <p>Preparation time: <%= recipe.preparation_time %>
         <% if recipe.preparation_time > 1  %>
           hours
           <% else  %>
          hour
         <% end %> </p>
         
        <p>Cooking time: <%= recipe.cooking_time %> 
        <% if recipe.cooking_time > 1  %>
           hours
           <% else  %>
          hour
         <% end %>
         </p>
     </div>
     <div class="form-check form-switch">
        <% if can? :manage, @recipe %>
          <%= form_with(model: @recipe) do |form| %>
            <%= form.check_box :public,onchange: 'this.form.submit();',class:"form-check-input"%>
            <label class="form-check-label" for="flexSwitchCheckDefault">public</label>
          <% end %>
        <% else %>
          <%= form_with(model: @recipe) do |form| %>
            <%= form.check_box :public, disabled: true,class:"form-check-input" %>
            <label class="form-check-label" for="flexSwitchCheckDefault">public</label>
          <% end %>
        <% end %>
      </div>
</div>

app/views/recipes/index.html.erb
<section>
  <div>
  <% if can? :create, @recipes.first %>
   <%= button_to "Add Recipe", new_recipe_path, method: :get, class:"btn btn-primary mx-4 my-2" %>
   <% end %>
  </div>
  <% if @recipes.exists? %>
      <% @recipes.each do |recipe| %>
      <div class="container-fluid">
        <div class="d-flex justify-content-around align-items-center border m-2">
          <div class="mx-4">
            <p><%= link_to recipe.name ,recipe_path(recipe.id) %></p>
            <% if can? :destroy, recipe %>
            <p><%= button_to "Remove", recipe_path(recipe.id), method: :delete, class:"btn btn-danger" %></p>
          <% end %>  
          </div>
          <div class="mx-4">
            <p><span class="w-50"><%= recipe.description %></span></p>
          </div>
        </div>
      </div>
      <% end %>
   <% else %>
          <p>No Recipe Added yet</p> 
      <% end %>
  <div>
</div>
</section>

app/views/recipes/new.html.erb
<p style="color: green"><%= notice %></p>

<h3 class="text-center">Add New Recipe</h3>

<%= render "form", recipe: @recipe %>

<br>

<div>
  <%= link_to "Back to recipes", recipes_path %>
</div>

app/views/recipes/public.html.erb
<h2 class="text-center">Public Recipes</h2>

<div id="recipes">
  <% @recipes.each do |recipe| %>
      <div class="container-fluid">
        <div class="d-flex justify-content-around align-items-center border m-2">
          <div class="m-3">
            <p class="fw-bold"><%= recipe.name %></p>
            <p><%= recipe.user.name %></p>  
          </div>
          <div class="m-3">
            <% if recipe.public == false%>
                <p><%= recipe.decription %></p>
            <% else %>
                <p>Total foods items: <%= RecipeFood.where(recipe_id: recipe.id).count %></p>
                <% price = RecipeFood.where(recipe_id: recipe.id).reduce(0) { |sum, f| sum + (f.quantity*Food.find(f.food_id).price).to_f } %>
                <p>Total price: $<%= price %></p>
            <% end %>
          </div>
        </div>
      </div>
  <% end %>
</div> 

app/views/recipes/show.html.erb
<p style="color: green"><%= notice %></p>

<section>
  <%= render "recipe", recipe: @recipe %>
  <p class="fw-bold mx-5">Steps go here...</p>
  <div class="d-flex justify-content-between mx-5" >
  <span>
    <%= button_to "Generate shopping list", general_shopping_list_index_path, method: :get, class:"btn btn-success" %>
    </span>
   <% if can? :create, @recipe %>
  <%= button_to "Add ingredient", new_recipe_recipe_food_path(@recipe), method: :get, class:"btn btn-light"  %>
   <% end %>
  </div>
  <div class="m-4">
    <table class="table border">
    <thead>
     <tr>
      <th>Food</th>
      <th>Quantity</th>
      <th>Value</th>
      <th>Action</th>
     </tr>
    </thead>
    
      <% @recipe_foods.each do |recipe_food| %>
      <tbody>
        <td><%= link_to recipe_food.food.name,food_path(recipe_food.food.id) %></td>
          <td><%= recipe_food.quantity %></td>
          <td>$<%= recipe_food.food.price * recipe_food.quantity %></td>
          <% if can? :destroy, @food %>
          <td class="d-flex gap-2">
          <%= button_to "Remove", recipe_recipe_food_path(@recipe, recipe_food), method: :delete, class:"btn btn-danger" %>
          <% end %>
         <button class="btn btn-primary">Modify</button></td>
      </tbody>
    <% end %>
  </table>
  </div>
  <%= link_to "Back to recipe", recipes_path %>
</section>