config/routes.rb
Rails.application.routes.draw do
  Rails.application.routes.default_url_options[:host] = "localhost:3000"
  get 'general_shopping_list/index'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  get 'public_recipes', to: 'recipes#public', as: 'public'
  root "recipes#public"
  resources :foods
  resources :recipes do
    resources :recipe_foods
    end
  resources :public_recipes
  resources :general_shopping_list

end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy
  has_many :recipes, through: :recipe_foods, dependent: :destroy

  validates :name, presence: true

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  validates :measurement_unit, presence: true, uniqueness: { case_sensitive: false }
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  def index
    @foods = current_user.foods.all
  end

  def new
    @food = current_user.foods.new
  end

  def create
    @food = current_user.foods.new(food_params)

    if @food.save
      flash[:success] = 'Food added successfully'
      redirect_to foods_path
    else
      flash.now[:error] = 'Error: Food could not be added'
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @food = Food.find(params[:id])
  end

  def destroy
    @food = Food.find(params[:id])
    if @food.destroy
      flash[:success] = 'Food was successfully deleted.'
      redirect_to foods_path
    else
      flash[:error] = 'Something went wrong'
      render :show
    end
  end

  def food_params
    my_food = params.require(:food).permit(:name, :measurement_unit, :price, :quantity)
    my_food[:user] = current_user
    my_food
  end
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/foods/_food.html.erb
<h1> <%= food.name %></h1>
<div id="<%= dom_id food %>">
     <p>Food: <%= food.name %></p>
     <p>Measurement unit <%= food.measurement_unit %></p>
     <p>Unit price $ <%= food.price %></p>
</div>

app/views/foods/_form.html.erb
<%= form_with model: food, url: foods_path  do |form| %>
    <div class="d-flex flex-column justify-content-center align-items-center">
      <div>
         <%= form.label :name %><br />
        <%= form.text_field :name, autofocus: true, autocomplete: "text" %>
        <% food.errors.full_messages_for(:name).each do |message| %>
          <div><%= message %></div>
        <% end %>
      </div>

      <div>
     <%= form.label :quantity %><br />
        <%= form.number_field :quantity, autofocus: true %>
        <% food.errors.full_messages_for(:quantity).each do |message| %>
          <div><%= message %></div>
        <% end %>
      </div>
      <div>
       <%= form.label :measurement_unit %><br />
        <%= form.text_field :measurement_unit, autofocus: true %>
        <% food.errors.full_messages_for(:measurement_unit).each do |message| %>
          <div><%= message %></div>
        <% end %>
      </div>
      <div>
        <%= form.label :price %><br />
        <%= form.number_field :price, autofocus: true %>
        <% food.errors.full_messages_for(:price).each do |message| %>
          <div><%= message %></div>
        <% end %>
      </div>
      <button type="submit" class="btn btn-primary m-2">Create Food</button>
    </div>
<% end %>

app/views/foods/index.html.erb
<section class="m-4">
  <div>
  <% if can? :create, @foods.first %>
   <%= button_to "Add Food", new_food_path, method: :get, class:"btn btn-primary float-end m-2" %>
   <% end %>
  </div>
  <% if @foods.exists? %>
  <table class="table border">
    <thead>
      <tr>
       <th>Food</th>
       <th>Quantity</th>
       <th>Measurement unit</th>
       <th>Unit price</th>
       <th>Action</th>
      </tr>
    </thead>
    
      <% @foods.each do |food| %>
      <tbody>
        <td><%= link_to food.name ,food_path(food.id) %></td>
          <td><%= food.quantity %></td>
          <td><%= food.measurement_unit %></td>
          <td>$<%= food.price %></td>
          <% if can? :destroy, food %>
            <td><%= button_to "Delete", food_path(food.id), method: :delete, class:"btn btn-danger" %></td>
          <% end %>
             </tbody>
      <% end %>
 
  </table>
   <% else %>
          <p>No Food Added yet</p> 
      <% end %>
  <div>
</div>
</section>

app/views/foods/new.html.erb
<p style="color: green"><%= notice %></p>

<h3 class="text-center">Add New Food</h3>

<%= render "form", food: @food %>

<br>

<div>
  <%= link_to "Back to foods", foods_path %>
</div>

app/views/foods/show.html.erb
<p style="color: green"><%= notice %></p>

<section>
  <%= render "food", food: @food %>
   <% if can? :destroy, @food %>
  <%= button_to "Delete this food", food_path, method: :delete %>
   <% end %>
    <%= link_to "Back to food", foods_path %>
</section>