config/routes.rb
Rails.application.routes.draw do
  Rails.application.routes.default_url_options[:host] = "localhost:3000"
  get 'general_shopping_list/index'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  get 'public_recipes', to: 'recipes#public', as: 'public'
  root "recipes#public"
  resources :foods
  resources :recipes do
    resources :recipe_foods
    end
  resources :public_recipes
  resources :general_shopping_list

end

app/views/layouts/_header.html.erb
<header class="header">
 <% if user_signed_in? %>
  <div><%= link_to "Recipe App", root_path %></div>
  <nav class="navbar">
    <ul>
         <li>
        <%= link_to "Food List", foods_path %>
      </li>
      <li>
        <%= link_to "Recipe List", recipes_path %>
      </li>
      <li>
        <%= link_to "Public Recipe", public_recipes_path %>
      </li>
      <li>
        <%= link_to "General Shopping List", general_shopping_list_index_path %>
      </li>
      <li>
        <%= button_to "Log out", destroy_user_session_path, method: :delete %>
      </li>
      <% else %>
      <% end %>
    </ul>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FoodApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= render partial: "shared/navbar" %>
    <%= yield %>
     <% flash.each do |name, message| %>
    <div class="<%= name %>"><%= message %></div>
    <% end %>
  </body>
</html>